# Generated by Django 6.0.1 on 2026-01-16 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activationtoken',
            name='clean_token',
            field=models.CharField(max_length=12, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='activationtoken',
            name='token',
            field=models.CharField(max_length=14, unique=True),
        ),
    ]
