# Generated by Django 6.0.1 on 2026-01-16 04:57

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_activationtoken_clean_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activationtoken',
            name='clean_token',
        ),
        migrations.AlterField(
            model_name='activationtoken',
            name='token',
            field=models.CharField(default=accounts.models.generate_activation_code, max_length=14, unique=True),
        ),
    ]
