# Generated by Django 6.0.1 on 2026-01-16 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_activationtoken_clean_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activationtoken',
            name='clean_token',
            field=models.CharField(max_length=12, null=True, unique=True),
        ),
    ]
