# Generated by Django 6.0.1 on 2026-01-16 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_activationtoken_clean_token'),
    ]

    operations = [
    ]
