# Generated by Django 6.0.1 on 2026-01-16 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_populate_clean_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activationtoken',
            name='clean_token',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
